/*
 * generated by Xtext
 */
package br.edu.sr.ifes.leds;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class LedsCodeV001UiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return br.edu.sr.ifes.leds.ui.internal.LedsCodeV001Activator.getInstance().getInjector("br.edu.sr.ifes.leds.LedsCodeV001");
	}
	
}
