/**
 * generated by Xtext
 */
package br.edu.sr.ifes.leds.validation;

import br.edu.sr.ifes.leds.validation.AbstractLedsCodeV001Validator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class LedsCodeV001Validator extends AbstractLedsCodeV001Validator {
}
