/*
 * generated by Xtext
 */
package br.edu.sr.ifes.leds.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LedsCodeV001UiModule extends br.edu.sr.ifes.leds.ui.AbstractLedsCodeV001UiModule {
	public LedsCodeV001UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
