/*
 * generated by Xtext
 */
package br.edu.sr.ifes.leds.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import br.edu.sr.ifes.leds.ui.internal.LedsCodeV001Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LedsCodeV001ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return LedsCodeV001Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return LedsCodeV001Activator.getInstance().getInjector(LedsCodeV001Activator.BR_EDU_SR_IFES_LEDS_LEDSCODEV001);
	}
	
}
