/*
 * generated by Xtext
 */
package br.edu.sr.ifes.leds;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class LedsCodeV001StandaloneSetup extends LedsCodeV001StandaloneSetupGenerated{

	public static void doSetup() {
		new LedsCodeV001StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

