/*
 * generated by Xtext
 */
package br.edu.sr.ifes.leds;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LedsCodeV001RuntimeModule extends br.edu.sr.ifes.leds.AbstractLedsCodeV001RuntimeModule {

}
