/**
 * generated by Xtext
 */
package br.edu.sr.ifes.leds.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#outline
 */
@SuppressWarnings("all")
public class LedsCodeV001OutlineTreeProvider extends DefaultOutlineTreeProvider {
}
