/*
 * generated by Xtext
 */
package br.edu.sr.ifes.leds.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import br.edu.sr.ifes.leds.services.LedsCodeV001GrammarAccess;

public class LedsCodeV001Parser extends AbstractContentAssistParser {
	
	@Inject
	private LedsCodeV001GrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected br.edu.sr.ifes.leds.ui.contentassist.antlr.internal.InternalLedsCodeV001Parser createParser() {
		br.edu.sr.ifes.leds.ui.contentassist.antlr.internal.InternalLedsCodeV001Parser result = new br.edu.sr.ifes.leds.ui.contentassist.antlr.internal.InternalLedsCodeV001Parser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getInterfaceApplicationAccess().getTypeAlternatives_0_0(), "rule__InterfaceApplication__TypeAlternatives_0_0");
					put(grammarAccess.getModuleBlockAccess().getAlternatives_3(), "rule__ModuleBlock__Alternatives_3");
					put(grammarAccess.getDataTypeAccess().getAlternatives(), "rule__DataType__Alternatives");
					put(grammarAccess.getExtendAccess().getAlternatives(), "rule__Extend__Alternatives");
					put(grammarAccess.getImplementAccess().getAlternatives(), "rule__Implement__Alternatives");
					put(grammarAccess.getAccessModifierAccess().getAlternatives(), "rule__AccessModifier__Alternatives");
					put(grammarAccess.getProjectAccess().getGroup(), "rule__Project__Group__0");
					put(grammarAccess.getInterfaceBlockAccess().getGroup(), "rule__InterfaceBlock__Group__0");
					put(grammarAccess.getInterfaceApplicationAccess().getGroup(), "rule__InterfaceApplication__Group__0");
					put(grammarAccess.getInfrastructureBlockAccess().getGroup(), "rule__InfrastructureBlock__Group__0");
					put(grammarAccess.getDatabaseBlockAccess().getGroup(), "rule__DatabaseBlock__Group__0");
					put(grammarAccess.getNameVersionAccess().getGroup(), "rule__NameVersion__Group__0");
					put(grammarAccess.getApplicationBlockAccess().getGroup(), "rule__ApplicationBlock__Group__0");
					put(grammarAccess.getApplicationBlockAccess().getGroup_3(), "rule__ApplicationBlock__Group_3__0");
					put(grammarAccess.getDomainBlockAccess().getGroup(), "rule__DomainBlock__Group__0");
					put(grammarAccess.getModuleBlockAccess().getGroup(), "rule__ModuleBlock__Group__0");
					put(grammarAccess.getServiceBlockAccess().getGroup(), "rule__ServiceBlock__Group__0");
					put(grammarAccess.getServiceBlockAccess().getGroup_3(), "rule__ServiceBlock__Group_3__0");
					put(grammarAccess.getEntityBlockAccess().getGroup(), "rule__EntityBlock__Group__0");
					put(grammarAccess.getEntityBlockAccess().getGroup_7(), "rule__EntityBlock__Group_7__0");
					put(grammarAccess.getRepositoryBlockAccess().getGroup(), "rule__RepositoryBlock__Group__0");
					put(grammarAccess.getRepositoryBlockAccess().getGroup_3(), "rule__RepositoryBlock__Group_3__0");
					put(grammarAccess.getEnumBlockAccess().getGroup(), "rule__EnumBlock__Group__0");
					put(grammarAccess.getEnumBlockAccess().getGroup_4(), "rule__EnumBlock__Group_4__0");
					put(grammarAccess.getMethodParameterAccess().getGroup(), "rule__MethodParameter__Group__0");
					put(grammarAccess.getMethodParameterAccess().getGroup_2(), "rule__MethodParameter__Group_2__0");
					put(grammarAccess.getKeyValueAccess().getGroup(), "rule__KeyValue__Group__0");
					put(grammarAccess.getExtendBlockAccess().getGroup(), "rule__ExtendBlock__Group__0");
					put(grammarAccess.getImplementBlockAccess().getGroup(), "rule__ImplementBlock__Group__0");
					put(grammarAccess.getImplementBlockAccess().getGroup_2(), "rule__ImplementBlock__Group_2__0");
					put(grammarAccess.getDataTypeListAccess().getGroup(), "rule__DataTypeList__Group__0");
					put(grammarAccess.getDataTypeSetAccess().getGroup(), "rule__DataTypeSet__Group__0");
					put(grammarAccess.getImportCompoundNameAccess().getGroup(), "rule__ImportCompoundName__Group__0");
					put(grammarAccess.getCompoundNameAccess().getGroup(), "rule__CompoundName__Group__0");
					put(grammarAccess.getCompoundNameAccess().getGroup_1(), "rule__CompoundName__Group_1__0");
					put(grammarAccess.getLedsCodeDSLAccess().getProjectAssignment(), "rule__LedsCodeDSL__ProjectAssignment");
					put(grammarAccess.getProjectAccess().getNameAssignment_1(), "rule__Project__NameAssignment_1");
					put(grammarAccess.getProjectAccess().getInfrastructureBlockAssignment_3(), "rule__Project__InfrastructureBlockAssignment_3");
					put(grammarAccess.getProjectAccess().getInterfaceBlockAssignment_4(), "rule__Project__InterfaceBlockAssignment_4");
					put(grammarAccess.getProjectAccess().getApplicationBlockAssignment_5(), "rule__Project__ApplicationBlockAssignment_5");
					put(grammarAccess.getProjectAccess().getDomainBlockAssignment_6(), "rule__Project__DomainBlockAssignment_6");
					put(grammarAccess.getInterfaceBlockAccess().getNameAssignment_1(), "rule__InterfaceBlock__NameAssignment_1");
					put(grammarAccess.getInterfaceBlockAccess().getInterfaceApplicationAssignment_3(), "rule__InterfaceBlock__InterfaceApplicationAssignment_3");
					put(grammarAccess.getInterfaceApplicationAccess().getTypeAssignment_0(), "rule__InterfaceApplication__TypeAssignment_0");
					put(grammarAccess.getInterfaceApplicationAccess().getNameAssignment_1(), "rule__InterfaceApplication__NameAssignment_1");
					put(grammarAccess.getInterfaceApplicationAccess().getNameAppAssignment_3(), "rule__InterfaceApplication__NameAppAssignment_3");
					put(grammarAccess.getInfrastructureBlockAccess().getBasePackageAssignment_4(), "rule__InfrastructureBlock__BasePackageAssignment_4");
					put(grammarAccess.getInfrastructureBlockAccess().getProjectVersionAssignment_7(), "rule__InfrastructureBlock__ProjectVersionAssignment_7");
					put(grammarAccess.getInfrastructureBlockAccess().getLanguageAssignment_11(), "rule__InfrastructureBlock__LanguageAssignment_11");
					put(grammarAccess.getInfrastructureBlockAccess().getFrameworkAssignment_16(), "rule__InfrastructureBlock__FrameworkAssignment_16");
					put(grammarAccess.getInfrastructureBlockAccess().getOrmAssignment_21(), "rule__InfrastructureBlock__OrmAssignment_21");
					put(grammarAccess.getInfrastructureBlockAccess().getDatabaseAssignment_26(), "rule__InfrastructureBlock__DatabaseAssignment_26");
					put(grammarAccess.getDatabaseBlockAccess().getVersionValueAssignment_2(), "rule__DatabaseBlock__VersionValueAssignment_2");
					put(grammarAccess.getDatabaseBlockAccess().getNameValueAssignment_6(), "rule__DatabaseBlock__NameValueAssignment_6");
					put(grammarAccess.getDatabaseBlockAccess().getUserValueAssignment_10(), "rule__DatabaseBlock__UserValueAssignment_10");
					put(grammarAccess.getDatabaseBlockAccess().getPassValueAssignment_14(), "rule__DatabaseBlock__PassValueAssignment_14");
					put(grammarAccess.getDatabaseBlockAccess().getHostValueAssignment_18(), "rule__DatabaseBlock__HostValueAssignment_18");
					put(grammarAccess.getNameVersionAccess().getNameValueAssignment_2(), "rule__NameVersion__NameValueAssignment_2");
					put(grammarAccess.getNameVersionAccess().getVersionValueAssignment_6(), "rule__NameVersion__VersionValueAssignment_6");
					put(grammarAccess.getApplicationBlockAccess().getNameAssignment_1(), "rule__ApplicationBlock__NameAssignment_1");
					put(grammarAccess.getApplicationBlockAccess().getApplicationDomainAssignment_3_1(), "rule__ApplicationBlock__ApplicationDomainAssignment_3_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			br.edu.sr.ifes.leds.ui.contentassist.antlr.internal.InternalLedsCodeV001Parser typedParser = (br.edu.sr.ifes.leds.ui.contentassist.antlr.internal.InternalLedsCodeV001Parser) parser;
			typedParser.entryRuleLedsCodeDSL();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public LedsCodeV001GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(LedsCodeV001GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
