/*
 * generated by Xtext
 */
package br.edu.sr.ifes.leds.ui.contentassist

import br.edu.sr.ifes.leds.ui.contentassist.AbstractLedsCodeV001ProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class LedsCodeV001ProposalProvider extends AbstractLedsCodeV001ProposalProvider {
}
